### ISSUE TITLE
Use latest node version

### ISSUE THREAD

**Issue by letientai299** [cuisines/gitlab-ci-react-native-android#1]
Thanks for this docker image, we got Gitlab CI enabled for our React Native. 

I have one suggestion regards nodejs version. In our CI build, we got this message:

```text
warning You are using Node "7.10.1" which is not supported and may encounter bugs or unexpected behavior. Yarn supports the following semver range: "^4.8.0 || ^5.7.0 || ^6.2.2 || ^8.0.0"
```

This can be fixed by just install newer node version (change this [line](https://github.com/cuisines/gitlab-ci-react-native-android/blob/e5ed6f47a94cff1b676f42cebe79a59c194b5b8a/Dockerfile#L57)). But why don't we just build up from one of the official node images?

**Comment by mtb77** [comment]
@thiemo--bleeken should we switch to Node 8 already?

**Comment by thiemo--bleeken** [comment]
@letientai299 we will update the version. thanks for the hint!

**Comment by letientai299** [comment]
I'm closing this as the request is done in 4d4a730843d2062dca55b821f44d76d9bbf37d93
