### ISSUE TITLE
react-native: command not found

### ISSUE THREAD

**Issue by asinel** [cuisines/gitlab-ci-react-native-android#4]
I am trying to bundle it, but is says "react-native" was not found. 

react-native bundle --platform android --dev false --entry-file index.android.js --bundle-output android/app/src/main/assets/index.android.bundle --assets-dest android/app/src/main/res
bash: react-native: command not found

**Comment by tsvetan-ganev** [comment]
This is probably because `react-native` isn't installed globally. You should add a script entry in your `package.json` which will reference the local binary (`node_modules/.bin/react-native`), e.g.:

```
"scripts": {
  "build-android": "react-native bundle --platform android --dev false --entry-file index.android.js --bundle-output android/app/src/main/assets/index.android.bundle --assets-dest android/app/src/main/res"
}
```

and then use it in the CI file like: `npm run build-android`
