### ISSUE TITLE
Android licenses not accepted (anymore)

### ISSUE THREAD

**Issue by Lythenas** [cuisines/gitlab-ci-react-native-android#7]
First of all thanks for providing this docker image. It really saved me a lot of time.

It worked perfectly until two days ago. Now my android build job fails because the licenses aren't accepted.

Here is the part of the log I think is useful:

```
Checking the license for package Android SDK Build-Tools 27.0.3 in /sdk/licenses
Warning: License for package Android SDK Build-Tools 27.0.3 not accepted.
Checking the license for package Android SDK Platform 27 in /sdk/licenses
Warning: License for package Android SDK Platform 27 not accepted.

FAILURE: Build failed with an exception.

* What went wrong:
A problem occurred configuring project ':app'.
> Failed to install the following Android SDK packages as some licences have not been accepted.
     platforms;android-27 Android SDK Platform 27
     build-tools;27.0.3 Android SDK Build-Tools 27.0.3
  To build this project, accept the SDK license agreements and install the missing components using the Android Studio SDK Manager.
  Alternatively, to transfer the license agreements from one workstation to another, see http://d.android.com/r/studio-ui/export-licenses.html
  
  Using Android SDK: /sdk
```

I tried to echo the hashes of my local license files on the server but I wasn't able to fix the issue.

**Comment by Lythenas** [comment]
I still wasn't able to get it to work by copying the hashes. But I temporarily fixed this by adding

```yaml
before_script:
  - echo -e "y\ny\ny\ny\ny\ny\ny\ny\n" | $ANDROID_HOME/tools/bin/sdkmanager --licenses
```

to my `.gitlab-ci.yml`.

Btw does anyone know if you are allowed to do it that way?

**Comment by alxndrsn** [comment]
@Lythenas perhaps more robust:
```
before_script:
  - yes | $ANDROID_HOME/tools/bin/sdkmanager --licenses
```

**Comment by mtb77** [comment]
@alxndrsn please create a pull request

**Comment by RaschidJFR** [comment]
> I still wasn't able to get it to work by copying the hashes. But I temporarily fixed this by adding

@Lythenas what exactly did you do that didn't work? I'm copied the license files into the repo and used in the CI process. It worked for me:

```bash
mkdir -p "$ANDROID_HOME"/licenses && cp licenses/* "$ANDROID_HOME"/licenses
```
